### ISSUE TITLE
ADSR Envelope pop up warning

### ISSUE THREAD

**Issue by LewisMacAudio** [nothke/unity-utils#3]
Hi again, I can't add the ADSR script as a component and get (can't add script component 'adsrenvelope' because the script class cannot be found. make sure that there are no compile errors and that the file name and class name match.) any help would be great!

Cheers
Lewis

**Comment by nothke** [comment]
ADSREnvelope is a struct, a value type, just like float or int, and not a MonoBehaviour class so it can't be attached on its own. 

To use it, you can make a new script that then holds a for example `public ADSREnvelope envelope` variable, it will be then exposed in the inspector. To update its internal clock and read the value off it, use `envelope.Update(inputSignal, deltaTime);`.

Here is an example of a script that uses the envelope:

```
using UnityEngine;
using Nothke.Utils;

public class SimpleADSRTest : MonoBehaviour
{
    public ADSREnvelope envelope = ADSREnvelope.Default();

    private void Update()
    {
        bool spacePressed = Input.GetKey(KeyCode.Space);

        float value = envelope.Update(spacePressed, Time.deltaTime);

        Debug.Log(value);
    }
}
```
